---
build_from:
  amd64: ghcr.io/new-usemame/calibre-web-nextgen:v4.1.40
  aarch64: ghcr.io/new-usemame/calibre-web-nextgen:v4.1.40
labels:
  org.opencontainers.image.title: Calibre-Web Automated
  org.opencontainers.image.licenses: GPL-3.0
  org.opencontainers.image.source: https://github.com/Cdower/hassio-addons
  org.opencontainers.image.documentation: https://github.com/Cdower/hassio-addons/tree/main/calibre-web-automated
